version: '3'
services:
  mldonkey:
    restart: unless-stopped
    image: jsiu/mldonkey
    container_name: mld
    logging:
      options:
        tag: "{{.Name}}"
    network_mode: host
    volumes:
      - ${MLD_CNF}:/mld/.mldonkey:rw
    #  - ${MLD_INC}:/mld/inc:rw
    #  - ${MLD_SHR}:/mld/shr:rw
    #  - ${MLD_TMP}:/mld/tmp:rw
    environment:
      - P_TZ=${TZ}
      - PUID=${MLD_UID}
      - PGID=${MLD_GID}